-- MySQL Script generated by MySQL Workbench
-- qui 30 nov 2023 07:07:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema minia_php
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minia_php
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minia_php` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `minia_php` ;

-- -----------------------------------------------------
-- Table `minia_php`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_php`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(255) NULL DEFAULT NULL,
  `cep` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_php`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_php`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `useremail` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `cep` VARCHAR(255) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `birth_date` DATE NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_php`.`company_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_php`.`company_user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NULL DEFAULT NULL,
  `id_company` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user` (`id_user` ASC) VISIBLE,
  INDEX `id_company` (`id_company` ASC) VISIBLE,
  CONSTRAINT `company_user_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `minia_php`.`users` (`id`),
  CONSTRAINT `company_user_ibfk_2`
    FOREIGN KEY (`id_company`)
    REFERENCES `minia_php`.`company` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_php`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_php`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_company` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_company` (`id_company` ASC) VISIBLE,
  CONSTRAINT `project_ibfk_1`
    FOREIGN KEY (`id_company`)
    REFERENCES `minia_php`.`company` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_php`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_php`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_project` INT NULL DEFAULT NULL,
  `id_company` INT NULL DEFAULT NULL,
  `id_user` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `upload_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_project` (`id_project` ASC) VISIBLE,
  INDEX `id_company` (`id_company` ASC) VISIBLE,
  INDEX `id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `file_ibfk_1`
    FOREIGN KEY (`id_project`)
    REFERENCES `minia_php`.`project` (`id`),
  CONSTRAINT `file_ibfk_2`
    FOREIGN KEY (`id_company`)
    REFERENCES `minia_php`.`company` (`id`),
  CONSTRAINT `file_ibfk_3`
    FOREIGN KEY (`id_user`)
    REFERENCES `minia_php`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_php`.`job_compensation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_php`.`job_compensation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_project` INT NULL DEFAULT NULL,
  `job` VARCHAR(255) NOT NULL,
  `num_people` INT NULL DEFAULT NULL,
  `compensation_value` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_project` (`id_project` ASC) VISIBLE,
  CONSTRAINT `job_compensation_ibfk_1`
    FOREIGN KEY (`id_project`)
    REFERENCES `minia_php`.`project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_php`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_php`.`permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_php`.`sub_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_php`.`sub_project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_project` INT NULL DEFAULT NULL,
  `planned_start` DATE NULL DEFAULT NULL,
  `actual_start` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `neighborhood` VARCHAR(255) NULL DEFAULT NULL,
  `num_people` INT NULL DEFAULT NULL,
  `estimated_audience` INT NULL DEFAULT NULL,
  `num_functions` INT NULL DEFAULT NULL,
  `estimated_cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `actual_cost` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_project` (`id_project` ASC) VISIBLE,
  CONSTRAINT `sub_project_ibfk_1`
    FOREIGN KEY (`id_project`)
    REFERENCES `minia_php`.`project` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_php`.`user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_php`.`user_permissions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `permission_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `permission_id` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `user_permissions_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `minia_php`.`users` (`id`),
  CONSTRAINT `user_permissions_ibfk_2`
    FOREIGN KEY (`permission_id`)
    REFERENCES `minia_php`.`permissions` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- Create default permissions
-- -----------------------------------------------------
INSERT INTO permissions (description) VALUES
  ('admin'),
  ('geral'),
  ('limitado');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
