-- MySQL Script generated by MySQL Workbench
-- dom 15 out 2023 20:00:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema minia_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minia_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minia_test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `minia_test` ;

-- -----------------------------------------------------
-- Table `minia_test`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_test`.`company` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_test`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_test`.`users` (
  `id` INT NOT NULL,
  `useremail` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_test`.`company_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_test`.`company_user` (
  `id` INT NOT NULL,
  `id_user` INT NULL DEFAULT NULL,
  `id_company` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_user` (`id_user` ASC) VISIBLE,
  INDEX `id_company` (`id_company` ASC) VISIBLE,
  CONSTRAINT `company_user_ibfk_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `minia_test`.`users` (`id`),
  CONSTRAINT `company_user_ibfk_2`
    FOREIGN KEY (`id_company`)
    REFERENCES `minia_test`.`company` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_test`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_test`.`project` (
  `id` INT NOT NULL,
  `id_company` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_company` (`id_company` ASC) VISIBLE,
  CONSTRAINT `project_ibfk_1`
    FOREIGN KEY (`id_company`)
    REFERENCES `minia_test`.`company` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `minia_test`.`sub_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_test`.`sub_project` (
  `id` INT NOT NULL,  
  `id_project` INT NULL DEFAULT NULL,
  `planned_start` DATE NULL DEFAULT NULL, 
  `actual_start` DATE NULL DEFAULT NULL,
  `end_date` DATE NULL DEFAULT NULL,
  `state` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `neighborhood` VARCHAR(255) NULL DEFAULT NULL,
  `num_people` INT NULL DEFAULT NULL,
  `estimated audience` INT NULL DEFAULT NULL,
  `num_functions` INT NULL DEFAULT NULL,
  `estimated_cost` DECIMAL(10,2) NULL DEFAULT NULL,
  `actual_cost` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_project` (`id_project` ASC) VISIBLE,
  CONSTRAINT `sub_project_ibfk_1`
    FOREIGN KEY (`id_project`)
    REFERENCES `minia_test`.`project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_test`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_test`.`file` (
  `id` INT NOT NULL,
  `id_project` INT NULL DEFAULT NULL,
  `id_company` INT NULL DEFAULT NULL,
  `id_user` INT NULL DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `upload_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_project` (`id_project` ASC) VISIBLE,
  INDEX `id_company` (`id_company` ASC) VISIBLE,
  INDEX `id_user` (`id_user` ASC) VISIBLE,
  CONSTRAINT `file_ibfk_1`
    FOREIGN KEY (`id_project`)
    REFERENCES `minia_test`.`project` (`id`),
  CONSTRAINT `file_ibfk_2`
    FOREIGN KEY (`id_company`)
    REFERENCES `minia_test`.`company` (`id`),
  CONSTRAINT `file_ibfk_3`
    FOREIGN KEY (`id_user`)
    REFERENCES `minia_test`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_test`.`job_compensation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_test`.`job_compensation` (
  `id` INT NOT NULL,
  `id_project` INT NULL DEFAULT NULL,
  `job` VARCHAR(255) NOT NULL,
  `num_people` INT NULL DEFAULT NULL,
  `compensation_value` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_project` (`id_project` ASC) VISIBLE,
  CONSTRAINT `job_compensation_ibfk_1`
    FOREIGN KEY (`id_project`)
    REFERENCES `minia_test`.`project` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_test`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_test`.`permissions` (
  `id` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `minia_test`.`user_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minia_test`.`user_permissions` (
  `id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `permission_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `permission_id` (`permission_id` ASC) VISIBLE,
  CONSTRAINT `user_permissions_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `minia_test`.`users` (`id`),
  CONSTRAINT `user_permissions_ibfk_2`
    FOREIGN KEY (`permission_id`)
    REFERENCES `minia_test`.`permissions` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;